### ISSUE TITLE
Missing documentation for required docker compose plugin

### ISSUE THREAD

**Issue by LookACastle** [TheRacetrack/racetrack#116]
Following the tutorial currently ends up failing at `make kind-up` as it's not made clear that `docker-compose` is a required component.

**Comment by JosefAssadERST** [comment]
Is what you get when you `apt install docker-compose-plugin` the same thing as what `pip install docker-compose`?

**Comment by iszulcdeepsense** [comment]
> Is what you get when you `apt install docker-compose-plugin` the same thing as what `pip install docker-compose`?

I think it's not the same thing. Docker compose plugin lets you run `docker compose up ...` command, while with standalone docker-compose you have to run `docker-compose up ...`.

**Comment by JosefAssadERST** [comment]
> Further following the tutorial it'll complain about not having any infrastructure plugins installed currently. A line should be added somewhere instructing the user to run `racetrack plugin install github.com/TheRacetrack/plugin-kubernetes-infrastructure`

Sorry for being a stickler but this is valid but orthogonal to this issue. Do you mind creating a separate issue? (one day when we're 10,000 commits in and we're bisecting we'll be grateful for this kind of discipline, and yes I know this just touches passive documentation, still it's the habit)

**Comment by LookACastle** [comment]
No problem, it's created as #118.
