### ISSUE TITLE
Redesign CLI syntax of racetrack client

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#123]
1. What's missing?
- `racetrack list` command to see the running fatmen as it's shown on Dashboard

2. Things to improve:
- For instance, `racetrack delete WORKDIR RACETRACK_URL` command.
  You need to pass working directory to take fatman name and version out from a local manifest file. What if you don't have the manifest and you want to delete something as an admin. Explicit parameters `--name`, `--version` would be more reasonable.

3. Use dedicated library for building CLI applications:
- `argparse` is terrible at building sub-commands tree
- maybe use Typer or Click instead

**Comment by JosefAssadERST** [comment]
`racetrack completion bash` and maybe zsh?

**Comment by iszulcdeepsense** [comment]
I think the best choice is to use [Typer](https://typer.tiangolo.com/).

Few facts / opinions:
- [typer](https://github.com/tiangolo/typer) has 10.2 k stars on Github
- [click](https://github.com/pallets/click/) has 13.4 k stars on Github
- Typer makes use of Click
- Typer has "automatic completion for all shells" <- that's what we're looking for
- the syntax of Typer is more concise, simpler than Click
- Both has good documentation, but Typer's docs seems to be more friendly IMO.
- Click has BSD-3-Clause license, while Typer is released under MIT license. That's funny as Typer is dependent of Click, so then you use both.
- Typer seems to be more modern, eg. by having type annotations support
- Typer has better support for [nested SubCommands](https://typer.tiangolo.com/tutorial/subcommands/nested-subcommands/) (we need that, eg. for `racetrack plugin install ...`)

**Comment by iszulcdeepsense** [comment]
Another idea: In some cases having positional argument `RACETRACK_URL` doesn't really make sense, it could be converted to optional parameter `--remote RACETRACK_URL`.
I'm thinking about recommending a simpler workflow so you can select your current environment in first place (just as you do with `kubectl config set-context --current --namespace=racetrack`):
```
racetrack config racetrack_url my-local-docker
```
and then call operations without passing redundant `RACETRACK_URL` each time:
```
racetrack list
racetrack logs fatman-A
racetrack delete fatman-A
```
This would be possible too:
```
racetrack list --remote=my-local-docker
```

**Comment by JosefAssadERST** [comment]
Yeah that _feels_ like a good idea. But we should maybe pressure-test that idea with some users. @nielshelsoe ?

**Comment by nielshelsoe** [comment]
@JosefAssadERST you choose to ping the guy that just has come back from maternity leave? I might think that there is a better person to come up with some useful insights

**Comment by JosefAssadERST** [comment]
Have chatted with Niels and Veronica, consensus is that the idea of setting context so avoid typing URLs (or RT alias) every single time is good.

**Comment by iszulcdeepsense** [comment]
Good. I can make it backwards-compatible for the most common commands, so it won't be a breaking change, ie. `racetrack deploy . WHERE` or `racetrack deploy . --remote=WHERE`
