### ISSUE TITLE
Grafana Fatman dashboard panel does not respect the time window specified for the dashboard it is in

### ISSUE THREAD

**Issue by JosefAssadERST** [TheRacetrack/racetrack#125]
![image](https://user-images.githubusercontent.com/63641218/212269251-c9133b8d-33f4-480b-85e7-8669f3674b47.png)

The total calls are total irrespective of the time range selected in the dashboard.

**Comment by iszulcdeepsense** [comment]
@JosefAssadERST 
It comes from the fact that this panel shows the current value of the metric so it always shows the number of total calls from the very beginning.
Do you know how to do that in Prometheus/Grafana to make the query show the "delta" within the selected interval?
I think something like this would work:
```
last(total_calls) - first(total_calls)
```
if only these functions `first` and `last`  existed.

**Comment by JosefAssadERST** [comment]
I'm not entirely sure. I could have a look at promql and see if I can figure it out though. This wouldn't happen to be a good first issue also would it? (wink wink nudge nudge)
