### ISSUE TITLE
Missing installation guide for non-local clusters

### ISSUE THREAD

**Issue by LookACastle** [TheRacetrack/racetrack#130]
I want to test racetrack running non-locally, [so I go here](https://github.com/TheRacetrack/racetrack/blob/master/docs/user.md#using-a-production-racetrack). It tells me to do as I did for the tutorial for deploying locally, except change the addresses. But in the tutorial, it makes me start a KInD cluster and install racetrack on it via a makefile. And thus, it fails.

As far as I can tell, there's no guide for how to install racetrack non-locally. That, or it's not easy to find the installation guide.

**Comment by JosefAssadERST** [comment]
If we think from the perspective of someone who has stumbled across this project, wouldn't the least surprising thing be like this?

1. Click the docs link
2. Click the "install" section
3. Click the "Kubernetes" section
4. See it just tells you to `kubectl apply -f path/to/kustomize/manifests`
