### ISSUE TITLE
Host local Grafana

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#144]
Standalone Grafana and Prometheus is now part of a "dev" profile when starting a local Racetrack with docker-compose.
It could be an official part of the Racetrack, as one of its components. 
This would give us a better control on provisioning Grafana dashboards.

The hard part is how Prometheus discovers the Jobs to scrape metrics from. 
The way of discovering jobs may depend on a infrastructure type being used by Racetrack, if it's either Kubernetes, local docker or remote docker daemon. What if multiple infrastructure plugins are in use?

Drawbacks:
- Racetrack will be composed of 2 more containers, becomes a bit more bloated.
- local Grafana won't have access to Kubernetes' metrics like CPU & Memory usage by pods, as opposed to the Grafana configured by kind Kubernetes providers.
- dynamic Jobs discovery may be troublesome. It may be a source of new issues.

**Comment by JosefAssadERST** [comment]
>  This would give us a better control on provisioning Grafana dashboards.

Agree. When considering that we can create dashboards automatically for jobs, this is potentially a big deal.

> The hard part is how Prometheus discovers the Jobs to scrape metrics from.

When in doubt, under-engineer. Is it an option when a new job is deployed it gets written to a file which a Prometheus  [`file_sd_config`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config) subsequently picks up from?

> Racetrack will be composed of 2 more containers, becomes a bit more bloated.

So far, that doesn't bother me. All it takes is one new ML model from @jsandroos and suddenly RT's resource usage is only 0.01% of the total resources required. :)

> local Grafana won't have access to Kubernetes' metrics like CPU & Memory usage by pods, as opposed to the Grafana configured by kind Kubernetes providers

Agree that's a loss. I mean we can still get it, but then we'd have to ship a dashboard json in `/contrib`which admins should install by hand (sort of like I think we already do).

Should we at some point consider if it's part of the responsibilities of an infrastructure target plugin (hereafter ITP) to be able to obtain from its infrastructure target instances operational metrics for running jobs?

Meaning, should the k8s ITP be able to query the k8s API to know how much RAM and CPU a given job is using?

> dynamic Jobs discovery may be troublesome. It may be a source of new issues.

Is this a new way to say that "less lines of code, fewer bugs"? :)

**Comment by iszulcdeepsense** [comment]
Thanks for pointing out the `file_sd_config` - I didn't know about that feature, I thought it needs restarting Prometheus for the changes to take effect. Fortunately, "Changes are detected via disk watches and applied immediately".

> Meaning, should the k8s ITP be able to query the k8s API to know how much RAM and CPU a given job is using?

Good thought. We may consider this also in terms of [Better monitoring of Job's condition](https://github.com/TheRacetrack/racetrack/issues/77)

> Is this a new way to say that "less lines of code, fewer bugs"? :)

Correct.
