### ISSUE TITLE
More granular deployment phases

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#145]
When you deploy a Job with a racetrack-client, you can see the output:
```
[2023-01-26 13:37:39] INFO  deployment in progress...
[2023-01-26 13:37:40] INFO  deployment in progress: building image...
[2023-01-26 13:37:41] INFO  deployment in progress: building image...
[2023-01-26 13:37:43] INFO  deployment in progress: building image...
[2023-01-26 13:37:46] INFO  deployment in progress: building image...
[2023-01-26 13:37:51] INFO  deployment in progress: building image...
[2023-01-26 13:37:56] INFO  deployment in progress: building image...
[2023-01-26 13:38:01] INFO  deployment in progress: building image...
[2023-01-26 13:38:06] INFO  deployment in progress: building image...
[2023-01-26 13:38:11] INFO  deployment in progress: building image...
...
```
While in fact, under the hood of "building image" a lot of different things happen:
- fetching the Job's source code
- building base image
- pushing base image to the registry
- building job image
- pushing the job image
- Optionally: building other images (in case of a Job composed of multiple containers)
- Optionally: pushing other images (in case of a Job composed of multiple containers)

For simplicity the racetrack-client could say: `building image (2/3)`, `pushing image (3/3)`

It could be more informative to know where the most of the time is spent on. Is it building images with a lot of requirements or pushing to the registry due to a throttled network?
It would be nice to have more granular image-builder's steps of the deployment phases.

**Comment by JosefAssadERST** [comment]
What happens with this implementation one day when we build an Amazon AMI or VMWare builder?

**Comment by iszulcdeepsense** [comment]
> What happens with this implementation one day when we build an Amazon AMI or VMWare builder?

I believe the interface is quite simple and general to handle that case:
Any Builder implementation will be able to update "phase" with an arbitrary string. 
If you don't, the result will be as it is now - you'll see `deployment in progress: building image...` (that's the default phase applied by Lifecycle in first place)

**Comment by JosefAssadERST** [comment]
> > What happens with this implementation one day when we build an Amazon AMI or VMWare builder?
> 
> I believe the interface is quite simple and general to handle that case: Any Builder implementation will be able to update "phase" with an arbitrary string. If you don't, the result will be as it is now - you'll see `deployment in progress: building image...` (that's the default phase applied by Lifecycle in first place)

Assume that the person developing an infrastructure target type plugin is someone we don't know and doesn't speak with us but is locked in the basement of a gray faceless corporation and has to develop this plugin against some alien infrastructure type.

As long as the API they should use is clear and the docs are straightforward we're probably good. One thought might be to make it an optional thing, the world is full of strange infrastructures and there might be some for whom this kind of hook is meaningless.

Just trying to think defensively.

**Comment by iszulcdeepsense** [comment]
Here's the sketch of the implementation, but first a bit of context how it works today.

## Context
*Deployment* entity in a database has a *phase* field  (nullable text column).

Lifecycle supervises the deployment process. Once the deployment is created, the *phase* is gradually updated by calling the following Lifecycle's function multiple times:

```python
def save_deployment_phase(deployment_id: str, phase: str):
    deployment = models.Deployment.objects.get(id=deployment_id)
    deployment.phase = phase
    deployment.update_time = now()
    deployment.save()
```

For instance, Lifecycle does this right before asking the image-builder to start the building process:
```python
save_deployment_phase(deployment.id, 'building image')
_send_image_build_request(...)
```

However, `save_deployment_phase` function is available only to Lifecycle (as the only service connected to the database), 
so image-builder can't update the deployment's phases.
That's about to be changed.

Image-builder can have different types of "builders", currently there's one - docker.

## Implementation
1. Lifecycle serves a new endpoint `PUT /deployment/{id}/phase` calling `save_deployment_phase` function under the hood.
2. Lifecycle sets the initial "building image" phase as usual.
3. The builder class of the image-builder makes calls to update the phase as it proceeds with the next steps.  This is opt-in feature, the builder is not obliged to yield the fine-grained phases.

Lifecycle sets "building image" phase right before calling the builder. So if the builder doesn't provide more granular steps, there will be a default one, given by Lifecycle, during this time.

**Note**: With that in mind, circular calls arise between *Lifecycle* and *Image-builder* (I don't want to use term "circular dependency"). *Lifecycle* calls *Image-builder* to build something. Then *image-builder* responds to Lifecycle few times, updating its progress. In this case I think it's acceptable.

**Comment by JosefAssadERST** [comment]
That's a sane proposal. I agree with it.

I think the only thing I'll add is (very tangentially to this issue), to begin to think about user experience for a new class of user. the Infrastructure Target Plugin (ITP) developer. I'm looking at the [plugin development docs](https://theracetrack.github.io/racetrack/docs/development/developing-plugins/) and we probably need to take a step back and be a lot more exhaustive and clear.

Of course the docs need to specify the ITP developer can use this new feature, but the docs also need to split up job type plugins and ITPs.
