### ISSUE TITLE
"perform" command to call a Job with CLI

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#146]
To facilitate testing, racetrack CLI client could have a `perform` command to call a Job's endpoint instead of building a curl query on your own. For instance:
```shell
racetrack perform adder "numbers: [40,2]"
```
will make the call to the Job called "adder" with the payload: `{"numbers": [40,2]}` and it will print out the result.

In this way, you can omit:
- URL of the Racetrack's remote - the current one will be taken
- your Racetrack User's Auth token - it will be taken from the local config
- `/api/v1/perform` path, the `--path` parameter can override it
- Job's version - `latest` by default, the `--version` parameter can override it
- obvious headers like `accept: application/json`, `Content-Type: application/json`
- POST method
- you don't even need to have `curl` installed (it doesn't have to be on-board on some uncivilized OS)

If you wish to generate a curl query from it, do
```sh
racetrack perform adder "numbers: [40,2]" --curl
```
and it will spit out:

```sh
curl -X 'POST' \
  'http://localhost:7105/pub/fatman/adder/latest/api/v1/perform' \
  -H 'accept: application/json' \
  -H 'X-Racetrack-Auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9' \
  -H 'Content-Type: application/json' \
  -d '{
  "numbers": [
    40,
    2
  ]
}'
```

**Comment by JosefAssadERST** [comment]
It's a good idea, we should kick the tires on it.

I see one difficulty right off the bat. There's no requirement for a Job type to have any endpoints at all, never mind one specifically called "perform". I don't think we can hardcode this specific thing in the CLI.

And yes that means that currently it's perfectly legal for a RT Job to say nothing; no callable endpoints. Not as strange as you might think, maybe I want to make a Job which just calls another one every 5 minutes (RT cron-alike).

**Comment by iszulcdeepsense** [comment]
In fact, every Job must have `perform` endpoint as stated here https://github.com/TheRacetrack/plugin-python-job-type/blob/master/docs/job_python3.md?plain=1#L276
I know it's the part of the python3 plugin's specifics and we could easily think of a job type plugin that doesn't have `perform` endpoint at all.

So maybe `--path` parameter should be required in order not to be inclined towards any of the job types?

**Comment by JosefAssadERST** [comment]
So here's an idea which has been developed without considering complexity or viability:

1. For a given job, RT should be able to enumerate exposed HTTP endpoints (first consulting the job type, then consulting the job; in the python3 example, this gives us `/perform`, `/live`, etc. as well as any auxiliary endpoints defined).
2. The client can query the server for available endpoints on a given job, drawing on the information compiled in above point
3. The client has a command `racetrack call --path relative/url/of/a/specific/endpoint`
4. Just to show off, the client autocomplete scripts can complete on the value of `relative/url/of/a/specific/endpoint`

I guess this hinges mainly on the viability of enumerating the actual endpoints of a job.
