### ISSUE TITLE
Set User-agent in all CLI requests

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#148]
It turns out that Cloudflare blocks requests with a user-agent containing “Python-urllib”! (https://github.com/IATI/IATI-Standard-Website/issues/230), but it's ok if the User-agent is set to `request`.

**Comment by JosefAssadERST** [comment]
Not to be Captain Hindsight, but have we asked the Kubernilla team if this is something they can adjust or fix on their end?

It's a great catch, but I feel bad having to mung our code to work around brain damage outside of our perimeter.

**Comment by iszulcdeepsense** [comment]
I understood it's automatic "feature" that can't be changed on Cloudflare, but now I see it can be adjusted. I could have explicitly asked, my bad.

At least we'll prevent from opening issues here like this https://github.com/IATI/IATI-Standard-Website/issues/230, complaining that Racetrack doesn't work with Cloudflare.

**Comment by JosefAssadERST** [comment]
🥓
