### ISSUE TITLE
Abandon adopting orphaned jobs

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#163]
Sometimes there's a chance to have empty manifests in the Jobs of Racetrack.
It happens when a job was created by other Racetrack instance and then it's found by another one and adopted, then we don't have a manifest in our database, cause we see only a name of a job.

Racetrack discovers wild jobs by labels. Infrastructure targets implement how to list jobs, eg. k8s infrastructure makes `kubectl get pods` with label filter. The result is compared with the database state and it can be used not only to check what's missing, but also to find out what's extra.

Racetrack shouldn't adopt "orphans" any longer. We gain nothing significant from it.

**Comment by JosefAssadERST** [comment]
I agree with the idea. Should there be admin facilities to reap them?

**Comment by iszulcdeepsense** [comment]
> I agree with the idea. Should there be admin facilities to reap them?

I think we aren't gonna need it. Can rethink it once the need arises.

**Comment by JosefAssadERST** [comment]
For these orphans, don't we have some sort of responsibility towards the owners of our infrastructure targets? On a bad day we could end up with a lot of orphans which are then taking up resources for no gain. That's why I was thinking of reaping.

The infrastructure admin can't just go do the reaping themselves since they don't know which of the pods with Racetrack labels are orphans and which are not.

**Comment by iszulcdeepsense** [comment]
Good point, it would be nice to do the reaping, but only Racetrack knows what to reap. 
I wonder how to notify the admin about such resources to spare. Here's the idea:
Lifecycle could print warning logs about the orphaned jobs (along with more details like pod names) and expose a Prometheus metrics with the amount of the orphaned jobs. Then, you could set up an alert in Grafana whenever number of orphans is greater than 0 and that's how Admin would be notified. He peeks into the logs and does the reaping then.

I'm not super crazy about user's convenience in this case, cause it's very unlikely to happen.

**Comment by JosefAssadERST** [comment]
That's pretty minimal, which I think is good. If we need to make it more complicated we can later.
