### ISSUE TITLE
Security concern related to config.yaml

### ISSUE THREAD

**Issue by blackplague** [TheRacetrack/racetrack#179]
I have some security concerns related to the config.yaml file that is created with the following path $HOME/.racetrack/config.yaml. It seem like the file is created with the following permissions o664, which makes it readable by everyone at least on a GNU/Linux like system. And the file hold potentially sensitive information such as racetrack tokens and git credentials.

```sh
ls -la ~/.racetrack/config.yaml
-rw-rw-r-- 1 $USER $USER 1828 Feb 16 11:47 /home/$USER/.racetrack/config.yaml
```

Proposed solution apply permission on file creation: 

On a GNU/Linux system it can be fixed by issuing on file creation: 
```python
p.chmod(0o600) # p being a Path object that hold the config.yaml file
```
On Windows system:
???

**Comment by JosefAssadERST** [comment]
Good point, I agree the file should be 0600.

We could also consider if RT should refuse to read it if it is something other than 0600, much like ssh does with keys.

I'm not very concerned with the Windows behavior at this stage.
