### ISSUE TITLE
use custom PostgreSQL schema instead of the public schema

### ISSUE THREAD

**Issue by JosefAssadERST** [TheRacetrack/racetrack#182]
Couple of reasons:

1. To avoid clobbering, if someone is using a shared database as backend for RT, and
2. To more easily manage access to the RT PostgreSQL relations (you have to revoke stuff with the public schema, which some people might not even have the luxury of doing, and it's easier to grant instead on a custom schema).

**Comment by iszulcdeepsense** [comment]
Fun fact: we already have a support for Postgres schemas other than "public". It was once used. It can be set with `POSTGRES_SCHEMA` env var. We can change it to `POSTGRES_SCHEMA=racetrack` to emphasize our recommendation and update racetrack config repo correspondingly.

**Comment by JosefAssadERST** [comment]
Can we remove LoC if we hardcode it to always be something we choose like "racetrack"? It was mainly configurable as a sort of ERSTism wasn't it?

**Comment by iszulcdeepsense** [comment]
Yes, we can add it to https://github.com/TheRacetrack/racetrack/blob/master/kustomize/kind/postgres.env. kustomize/kind is a sort of k8s configuration sample.

**Comment by iszulcdeepsense** [comment]
> Why would we ever need to tweak the RT DB schema name?

A long time ago, we had a DW database server for Racetrack.
It was shared by many applications, so we got dedicated `racetrack` database on it.
Moreover, there was only 4 such servers (dev, test, preprod, prod), so dev database had to handle all dev environments (dev-c2, dev-irek, dev-hubert, etc.). That's why we split them up by means of schemas: one database "racetrack" and `dev-irek`, `dev-c2` schemas.

**Comment by JosefAssadERST** [comment]
So our need to parametrize the DB schema name is an ERST-ism? :)

**Comment by iszulcdeepsense** [comment]
> So our need to parametrize the DB schema name is an ERST-ism? :)

Right

**Comment by JosefAssadERST** [comment]
Do we want to un-parametrise it?

**Comment by iszulcdeepsense** [comment]
I'd leave that option in case if there's a similar company called REST that has the same need as we did. I would change the default schema to "racetrack" though.
