### ISSUE TITLE
when a job has operational difficulties, the dashboard still says it's running

### ISSUE THREAD

**Issue by JosefAssadERST** [TheRacetrack/racetrack#190]
In a RT instance using the k8s infrastructure target, we've experienced that one of the jobs died. Meaning, in prometheus, `up()` returned 0. This happens sometimes, this isn't a problem.

But when this happens sometimes, it feels somehow misleading for the job in RT dashboard to say it's running in a green label.

When RT dashboard says "running" doesn't it actually mean "I deployed it to the selected infrastructure target successfully and to my knowledge it's still deployed there"? That's not 100% the same as "Running".

**Comment by iszulcdeepsense** [comment]
Lifecycle checks the status of the job every minute. It probes `/live` and `/ready` endpoints to figure out if the job is really running.
So when prometheus can't reach it, it should also be reported by Lifecycle and the status should be changed to "Error". Nevertheless, there might be some delay in doing so as the status is updated periodically. 
Maybe it was a short downtime (eg. switching pods by a replica set) or it was the problem with Prometheus itself.

**Comment by JosefAssadERST** [comment]
Ah interesting. Yeah that sounds like it was too brief. I don't know how to provoke it, but I know they occur very briefly almost every day, so I know to look out for it. When it occurs I'll try to hop in to the dashboard quickly and verify that it no longer says "running". In which case this issue is invalid.

**Comment by iszulcdeepsense** [comment]
If that happens, we can also peek into the lifecycle-supervisor's logs . There should be the trace if it finds some job in ERROR state.

**Comment by JosefAssadERST** [comment]
I'll just say, I had an opportunity earlier (documented on Teams) where we got an alert that a job was down. It showed as running the whole time in the RT dashboard and all of that job's pods showed as fine also in the k8s dashboard.

**Comment by iszulcdeepsense** [comment]
Closing as there's no sign of it after merging https://github.com/TheRacetrack/racetrack/pull/377 fix into master.
