### ISSUE TITLE
Documentation for job plugin development is too sparse

### ISSUE THREAD

**Issue by LookACastle** [TheRacetrack/racetrack#199]
The job plugin development docs are too sparse, and expect a prospective developer to know a lot of stuff ahead of time - I think we should point them in the right direction a bit more.

"_You MAY implement swagger documentation for your endpoints on root endpoint._" should really have documentation for how to make a swagger endpoint. A link to the documentation on their side is probably adequate.

"_You MAY implement /metrics endpoint for exposing Prometheus metrics._" should also have documentation, exactly like described above.

It'd also be nice if, like the required steps, these optional steps had example code written for them. 

The "Overall workflow" is very narrow to only the initial concept of racetrack. It needs to be expanded to be understandable to a wider audience, if we want to keep it around at all. Not every racetrack user has to have data scientists. Kubernetes is not the only infrastructure supported by racetrack. So on, so forth.

**Comment by iszulcdeepsense** [comment]
Let's revise this guide and let's make it to use [Go Job Type](https://github.com/TheRacetrack/plugin-go-job-type) as an example. Go would be better received and it has swagger docs already implemented.

**Comment by LookACastle** [comment]
I've created an [issue](https://github.com/TheRacetrack/plugin-go-job-type/issues/3) for this and have assigned myself.
