### ISSUE TITLE
Add link to Grafana on the Dashboard

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#206]
These useful links could include Grafana as well:

![Screenshot from 2023-03-14 17-29-46](https://user-images.githubusercontent.com/45496492/225073059-22c4ec1b-0e17-4127-b940-a07ef96d5945.png)

**Comment by JosefAssadERST** [comment]
Yes please!

If we have a per-job dashboard then it would be awesome to link to those from the panel you get when you click a job in the list of jobs accordion.

If we don't have a per-job dashboard maybe we should have one?
