### ISSUE TITLE
Add lang/jobtype column to racetrack-client list command

### ISSUE THREAD

**Issue by zcg909** [TheRacetrack/racetrack#207]
It would be nice if racetrack-client's list command could return a column with the jobs' `lang`s 

Currently, this is not an option with racetrack-client v. 2.10.1

**Comment by iszulcdeepsense** [comment]
Good idea. It will be easy to do right after merging https://github.com/TheRacetrack/racetrack/pull/205

**Comment by JosefAssadERST** [comment]
Good idea Dr. ZCG Number 909.

by the way, if you pipe the output into another command it drops the fancy formatting, right?

**Comment by iszulcdeepsense** [comment]
> by the way, if you pipe the output into another command it drops the fancy formatting, right?

Nope, just checked that `racetrack list | cat` gives the same output, including ANSI color chars.
