### ISSUE TITLE
Jobs stay visible after deletion via the dashboard.

### ISSUE THREAD

**Issue by LookACastle** [TheRacetrack/racetrack#211]
If you delete a job from the dashboard,the job stays on the dashboard, leaving stale data visible until you refresh the page. Ideally there wouldn't be stale data - I.E, the job shouldn't be shown any longer once deleted.

**Comment by JosefAssadERST** [comment]
Agree. Do we have the backend endpoint so the accordion can just be refreshed with an ajax call?

**Comment by iszulcdeepsense** [comment]
There's no backend endpoint for just the accordion, but the whole page. It makes me think of React so that components get refreshed once something changed in a reactive way.
