### ISSUE TITLE
Refresh jobs list on Dashboard

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#239]
Some people requested for automatic refreshing the jobs page whenever any change has been applied in the meantime or new job popped in.
We can use Socket.io library (which is already used by racetrack-client and Lifecycle for following logs), it works on top of websockets, falling back to long polling.

**Comment by JosefAssadERST** [comment]
I agree websockets are a good choice of mechanism here.

Only downside is, websockets assume the client is a web browser. So it makes it harder to share serverside endpoints between browser and CLI clients.

**Comment by iszulcdeepsense** [comment]
Another downside (or challenge) is the fact that we got 3 replicas of a Lifecycle server. And when some change has been applied to one of them, it has to be broadcasted further to notify all of the connected clients. And that would need some sort of MQ or cache, like Redis (or shared filesystem volumes?).

**Comment by JosefAssadERST** [comment]
Huh why? All 3 replicas would have their own websocket connection to the backend.

**Comment by iszulcdeepsense** [comment]
> Huh why? All 3 replicas would have their own websocket connection to the backend.

"All 3 replicas" are "backend". To be more specific, I wonder how to notify "Lifecycle 1" server, which one client is connected to, whereas some other guy submitted his change to "Lifecycle 3".

![image](https://user-images.githubusercontent.com/45496492/236779541-7f5b4ba5-b0ed-416f-9e4e-ded7ed35bcd1.png)

**Comment by mpolomdeepsense** [comment]
I found this: [https://tsh.io/blog/how-to-scale-websocket/](https://tsh.io/blog/how-to-scale-websocket/). I think the `Horizontal scaling with WebSocket Issue #2: Broadcasting` section is the problem that you described.

It's in JS (Node.js) but the overall idea behind the solution is more important.
