### ISSUE TITLE
Deploy jobs from URL

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#240]
It would be great if the Racetrack client could deploy jobs using a Manifest YAML file from a URL rather than requiring a local file.

For instance, if you'd like to deploy a community job, normally you'd need to clone the repository:
```
git clone github.com/iszulcdeepsense/racetrack-quake
cd racetrack-quake
racetrack deploy quake3/job.yaml
```
Instead, you could just do:
```
racetrack deploy https://raw.githubusercontent.com/iszulcdeepsense/racetrack-quake/master/quake3/job.yaml
```
Anyways, the source code is not taken from your local computer, but from git repo.

It resembles `kubectl` abilities:
```sh
kubectl apply -f https://git.io/blah # create resource(s) from url
# or
curl https://gist.githubusercontent.com/resource.yaml | kubectl apply 
```

**Comment by JosefAssadERST** [comment]
On the one hand, that's a neat idea.

On the other hand, is that a solution looking for a problem?

**Comment by iszulcdeepsense** [comment]
> On the other hand, is that a solution looking for a problem?

Do you mean downloading URLs on our own is looking for a problem? If that's the case, we can go with something more general, ie. reading from stdin, and delegate URL fetching to external tools: 
```
cat job.yaml | racetrack deploy
curl https://gist.githubusercontent.com/job.yaml | racetrack deploy
cat /dev/random | racetrack deploy
perl -MYAML::Merge::Simple=merge_files -MYAML -E 'say Dump merge_files(@ARGV)' f1.yaml f2.yaml | racetrack deploy
```
this would make it more usable in non-interactive scripts.
I admit, it's a low-priority thing. No one asked for it (yet), but it presume it could be appreciated at some point.

**Comment by JosefAssadERST** [comment]
Don't get me wrong, I like it. But, is this:

> No one asked for it (yet), but it presume it could be appreciated at some point

maybe the essence of [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)?

**Comment by anders314159** [comment]
I see 2 two ways to implement the above:

**1.** Make a temp directory, pipe input from stdin to `tmp_folder_xyz/job.yaml`, and use `tmp_folder_xyz/` as the `workdir` parameter.
**2.** Rewrite the send_deploy_request -> validate manifest to accept something besides paths.

Pros/cons:
**1.** feels like a wrapper and needs disk access.  But it doesn't touch the rest of the codebase, which is a huge boon.
**2.** is might not require disk access, but would require messing with a lot of code.

For both, the piped `job.yaml` would also need to be aware of the fact that the files it references are not local, like in https://github.com/iszulcdeepsense/racetrack-quake/blob/master/quake3/job.yaml.

**Comment by iszulcdeepsense** [comment]
@anders314159 I see now. Indeed, the code now assumes it operates on regular paths in many places.
I agree that making temp directory might not always work as it needs disk access, so I'm more inclined to **2.** option, if that's viable.
It reminds me of other feature of Racetrack - installing plugins with URI (whether it's a link, or a file). You can take a look at this wrapper function  https://github.com/TheRacetrack/racetrack/blob/92814364208efca26e88dbbab9703e44d51fe842/racetrack_client/racetrack_client/plugin/install.py#L105C1-L126C1 and maybe get inspired by this.

> For both, the piped job.yaml would also need to be aware of the fact that the files it references are not local, like in https://github.com/iszulcdeepsense/racetrack-quake/blob/master/quake3/job.yaml.

As for the references to local files, like `requirements.txt`, don't worry about it. This reference is used when building the image, and the repository is git-cloned on the server, so the files exist then.
Manifest YAML is the only file being read locally, the rest of the files are taken from git by Racetrack.
The only exception are secret vars, read locally as well, but in this case, racetrack could abort with an error.
