### ISSUE TITLE
PUB's remote gateway to access other infrastructure

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#300]
For the sake of these plugins' issues, requesting for remote tunnels:
- [Dual cluster setup](https://github.com/TheRacetrack/plugin-remote-kubernetes/issues/1)
- [Access jobs through tunneled ports](https://github.com/TheRacetrack/plugin-docker-daemon-deployer/issues/2)

it would be nice to support remote "tunnels" natively by Racetrack, that is, let the plugins to set up the communication between "racetrack" host and the "jobs" host.

I figured out that we don't necessarily need **encrypted** Wireguard tunnel or SSH tunnel. Simple **authorized** proxy / backdoor / bastion (whatever you call it) should be enough. Furthermore, setting up the Wireguard might not even be possible, if kubernetes' ingress controller only allows for the HTTP traffic (due to service routing by a base path).

![Screenshot from 2023-08-14 13-53-14](https://github.com/TheRacetrack/racetrack/assets/45496492/fd7d5657-8069-4764-82b2-5ee3cc745eca)

The idea is to turn the remote PUB into a "peer" mode that forwards the requests to the jobs, only if the auth header (for inter PUB communication) is valid. That way, you can't speak to the jobs directly in an unauthorized manner.

Setting up the "tunnel" (actually, it's not a true encrypted tunnel) needs the following steps:
1. configure PUBs properly (set host addresses, choose mode)
2. Install peer PUB (pod / container) on infrastructure target
3. Install infrastructure plugin
4. Configure infra plugin: k8s certificate (or other thing depending on the plugin), kube-api address, peer PUB address

Note that extending the PUB's functionality and installing additional services is a big thing, it goes beyond the plugin's responsibilities (as it is now), so the manual steps are required.

**Comment by JosefAssadERST** [comment]
> we don't necessarily need encrypted Wireguard tunnel or SSH tunnel

It would be very nice though. Are there advantages to not using encryption?

> setting up the Wireguard might not even be possible, if kubernetes' ingress controller only allows for the HTTP traffic 

Is that normal practise in k8s? Keep in mind, an ITP can require reasonable things from targets. So if it's normal practise for an ingress controller to only allow HTTPS, then we can require in the k8s ITP that targets do this. Then if someone doesn't, we don't support that and anyhow they're deviating from normal and good practises.

**Comment by iszulcdeepsense** [comment]
> Are there advantages to not using encryption?

The only advantage is simplicity and probably easier setup.

> Is that normal practise in k8s?

I guess that normal practise is to use NodePort (instead of ingress controller) to expose services outside with Wireguard: https://github.com/ivanmorenoj/k8s-wireguard. This setup looks not really infrastructure-independent though. I'd love to find something that works on both k8s and docker daemon, if possible.

**Comment by iszulcdeepsense** [comment]
Here's the updated diagram:
![Screenshot from 2023-08-31 10-29-07](https://github.com/TheRacetrack/racetrack/assets/45496492/c9255529-2dec-4795-9601-aec21ac52f29)
