### ISSUE TITLE
Add to docs: What makes Racetrack so special?

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#301]
I happen to hear it quite often: "Okay, but how is it different from other platforms?".
I think we need to explain this on the Racetrack's home page: "What distinguishes Racetrack?"

Stating what Racetrack does (and what it doesn't)  is also self-explanatory about what the Racetrack really is.

**Comment by JosefAssadERST** [comment]
Yeah we haven't really got a good elevator pitch yet.
