### ISSUE TITLE
Deploy new jobs through Dashboard

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#306]
You can already edit manifest of the job and you can redeploy one in a Dashboard UI, but you can't create a new one by submitting a manifest.
Users should be able to do `racetrack deploy` in a Dashboard, assuming they already pushed their code to git.

Most likely, secret vars won't be supported in this scenario.

**Comment by JosefAssadERST** [comment]
Has this been requested?

**Comment by iszulcdeepsense** [comment]
Yes, I can proudly say it's been requested by @mpolomdeepsense and I wanted this as well.
