### ISSUE TITLE
Simplify prerequisites to try racetrack out locally

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#307]
Some people say that [tutorial for setting up Racetrack](https://github.com/TheRacetrack/racetrack/blob/master/docs/user.md?plain=1#L214C1-L229C53) looks a bit scary. 10 steps of prerequisites? And you have to launch Kubernetes locally? That might be a high entry threshold.

In fact, there is lot less "real" prerequisites, but the total number of 10 looks dreadful. " A workstation with a sane operating system" - consider it done, "bash" - done, "curl" - done. So maybe it's not worth to mention it at all. Plus, k9s is an optional step, we can skip that too, I guess. Besides, "racetrack-client" is not a prerequisite - it gets installed in later steps.

There is another [Quickstart document](https://github.com/TheRacetrack/racetrack/blob/master/docs/quickstart.md) for getting started with racetrack. This  one doesn't rely on kubernetes but on docker. Maybe it's worth to sort this out, which is an official, recommended way to get started by a newcomer.

**Comment by JosefAssadERST** [comment]
Quickstart is nicer. What some projects do is, they just rely on quickstart and from there focus on actually using the system; then there's a separate section in the docs for putting it in operation.

Of course you know I feel strongly that k8s should be an option for production deploys, not a requirement.

**Comment by iszulcdeepsense** [comment]
Well, so maybe renaming "Tutorial" section (from User Guide) into "Local setup on Kubernetes" will do the trick.
