### ISSUE TITLE
Implement finer grained Access Control

### ISSUE THREAD

**Issue by LookACastle** [TheRacetrack/racetrack#309]
Currently, as far as I can see, our access control does not easily allow us to discriminate between jobs, job families, and so on. Yet, it is easy to imagine a scenario in which we have 2 users on the same instance who might not be comfortable with each other having access to everything on each others jobs, yet still want to share the same instance.

**Comment by iszulcdeepsense** [comment]
Have you seen https://theracetrack.github.io/racetrack/docs/permissions/?
You can narrow down  the access to job family, single job or even a single endpoint, though it's not easily manageable right now - it has to be done by means of Django's admin panel page.

**Comment by LookACastle** [comment]
I ended up looking at this documentation https://github.com/TheRacetrack/racetrack/blob/master/docs/admin.md#permissions which didn't mention the same thing, and after getting lost in Django concluding that you probably just couldn't.

If everything concerning this is already implemented then I'm guessing the issue is more or less solved - or, should at the very least be renamed. Leave it up until the end of the week though, I was asked to create an issue somewhat to this effect, so I'll give people time to object in case I had just misunderstood them.

**Comment by iszulcdeepsense** [comment]
@LookACastle  If the documentation led you astray, that's a one good reason to keep this issue and fix it at least.

**Comment by JosefAssadERST** [comment]
Bit of context here, we might be getting a second organization using the same RT instance as ML Lab. We don't want to let them get bored, drink cheap whiskey, and start deleting our ML models.

So the need is actually to begin to use the access control we already have to make it a bit less Wild West.

It might actually not be as straightforward as you think. Maybe you think "ok, so people can only see the models they own" but then you'll get irate ML Lab users who can't help each other out, or irate job portfolio managers who can't see all *their* models (note the careful choice of words: *their* models. Not the second organisation's models).

So there's probably a bit of design work to be done here.

That explanation probably should prompt a restatement of the issue title and body.

---

NB: it's not invalid to say "the solution is, no change to RT codebase, we stand up a separate RT instance". But before we go there, we look at this need and see if it might contain changes we'd like anyhow in RT.
