### ISSUE TITLE
Download zipped plugin from a Dashboard

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#451]
Sometimes it may come in handy to allow downloading the uploaded plugins through the Dashboard.
This would speed up the process, where we want to promote a version of a plugin running on dev environment to higher environments, like test or prod. Downloading the zip plugin will make sure that exactly the same version would be uploaded to the other places.

**Comment by anders314159** [comment]
I think also adding this option to the CLI makes sense
