### ISSUE TITLE
Add tls certificate to base image

### ISSUE THREAD

**Issue by gaprop** [TheRacetrack/racetrack#468]
Add root ca certificate to the base image in order to enable tls to erst services

It should only be something like:

- Copy the root ca certifcate to /usr/local/share/ca-certificates
- run update-ca-certificates

Message me (andkil) and I'll send the root ca certifcate to you

**Comment by iszulcdeepsense** [comment]
Alright, looking forward to updates.
I'm a bit reluctant to bake Erst specifics into the core image, but I believe it can be done just as well by mounting a file into a container.

**Comment by iszulcdeepsense** [comment]
closing and solving somewhere else
