### ISSUE TITLE
Collect user feedback when Stuff Goes Wrong©

### ISSUE THREAD

**Issue by anders314159** [TheRacetrack/racetrack#476]
I think that it is valuable to solicit and collect user feedback whenever Stuff Goes Wrong© for the user in Racetrack.

For example, a Racetrack user deploys, but the deployment Goes Wrong©. In the UI, or CLI, a small non-annoying Thing™ appears and asks "Hey, the deploy looks bad - do you have any feedback for the Racetrack admin regarding this?". The user can then select either:

1. "I fucked up", and then Racetrack admin doesn't care too much.
2. "Racetrack fucked up for reason X", and the user can write a comment and a Racetrack admin should probably look at it along with related logs.
3. "Solar radiation flipped a bit, blame the Sun", and Racetrack admin doesn't really know what the Sun is and doesn't care too much.
4. Or ignore the Thing™ entirely.

The Racetrack admin can then collect feedback and make an issue here summarizing frequent problems.

This is a very vibe'y question, and I am not sure if anyone has asked for this, but maybe Ford's Faster Horses quote applies.

**Comment by anders314159** [comment]
Reasons why it is a bad idea:
1. It creates multiple channels of feedback - the user is unsure if face-to-face feedback to admin is better than Thing™ feedback.
2. The admins might ignore it.
3. This feels a bit like creating Jira tickets, which should be avoided according to [this](https://en.wikipedia.org/wiki/Geneva_Conventions).
4. The users might ignore it.
5. The users might use it, and get frustrated if it feels like their feedback is taking too long to be addressed.
6. etc.
7. Are we gonna need it?
8. Are we gonna use it?

**Comment by JosefAssadERST** [comment]
Hm. It's an interesting idea, but my instinct is to push back (I don't like pushing back because I like brainstorms and thinking outside the box, and a blanket no discourages this).

If something goes wrong, I prefer for the software to tell me what the problem was, not the user. Via better logs for example.

I can't really think of any other software that does this kind of thing. Maybe stuff like Microsoft productivity software?

**Comment by anders314159** [comment]
On balance, I also don't think we should do it right now - the projects using RT right now is fairly small, and I think the feedback loop is okay right now.

But imagine a scenario where a single Racetrack instance is serving millions of users (next year, at the latest) - e.g. if a user keeps cancelling deployments because they take too long, it would be nice to know that, in addition to logs.

I've seen something like this feature in phone apps, and I heard in a podcast that Facebook ([caveat](https://en.wikipedia.org/wiki/Cargo_cult)) did this for their ml model deployment platform.

I'll close this, since it isn't really "an issue" and we agree to not do it<sup>right now</sup>, but where would discussions like this otherwise go?

**Comment by JosefAssadERST** [comment]
> if multiple users keep cancelling deployments because they take too long, it would be nice to know that, in addition to logs

This kind of information should come to the instance admin from RT, the admin shouldn't have to go looking for it. For example, tracking build time and cancellations, having those in Prometheus metrics, and having alerts or Grafana alarms.

That we control and can implement. Users will just send us nudes when they get mad.
