### ISSUE TITLE
Create ESC from the Dashboard

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#484]
> we made a new ESC in dev, but this new user does not appear in the list of Auth subjects.

Auth subject wasn't created for ESC. That's wrong. I checked that it gets created only if an ESC is created by an API endpoint `POST /api/v1/escs`, but if it's done manually in the Admin panel, then the Auth subject model is gone and has to be created manually too.

I guess we need a new Dashboard page for managing ESCs to make it less surprising and to use the proper endpoint under the hood.

**Comment by JosefAssadERST** [comment]
Shouldn't we actually be thinking of taking what we use the Django dashboard for and reflecting it in the RT dashboard, in general?

**Comment by iszulcdeepsense** [comment]
Yes. Django was a good kick starter. Common use cases should be in the dashboard after all. Now it's a good time for this, especially with the https://github.com/TheRacetrack/racetrack/issues/480 on the horizon.
