### ISSUE TITLE
If there are multiple kubernetes infrastructure target plugins installed, a single job are listed in multiple infrastructure targets in the admin page.

### ISSUE THREAD

**Issue by anders314159** [TheRacetrack/racetrack#489]
![image](https://github.com/TheRacetrack/racetrack/assets/45283827/b7121a81-4764-475d-9e1e-f66eff470cc1)

I think it's kinda confusing that hovering the blue 1 in the screenshot says "1 Jobs is using this infrastructure target" for both 1.5.1 and 1.5.0. Do jobs really run on two IF targets at the same time?

**Comment by iszulcdeepsense** [comment]
Right, that might be confusing and misleading. I think racetrack should prohibit that kind of situation innately.
It doesn't make sense to have multiple versions of the same infrastructure targets. If they coexist, they're fighting with each other. They discover the same jobs twice and they step on each other's toes by overwriting the same jobs.
Fortunately, when deploying a job, only the one (newer) is used.

At this point, plugins can be installed multiple times with different versions. That makes sense for job type plugins, whereas it's kind of pointless for infra plugins. So maybe we could restrict this behavior when detecting "infrastructure" plugin.

**Comment by anders314159** [comment]
If there already is an infrastructure plugin with the same name, we can replace it. Should we require that the [replace flag](https://github.com/TheRacetrack/racetrack/blob/dad59b582cecd06d109f709086fe4b2e015e2adc/lifecycle/lifecycle/endpoints/plugin.py#L82) is set before replacing the infrastructure plugin, or should it just be implicit that the user replaces the previous plugin when they upload a new one?

**Comment by iszulcdeepsense** [comment]
> If there already is an infrastructure plugin with the same name, we can replace it. Should we require that the [replace flag](https://github.com/TheRacetrack/racetrack/blob/dad59b582cecd06d109f709086fe4b2e015e2adc/lifecycle/lifecycle/endpoints/plugin.py#L82) is set before replacing the infrastructure plugin, or should it just be default that the user replaces the previous infrastructure plugin when they upload a new one?

Good question. I think Racetrack could raise an error and require replacing it explicitly.
