### ISSUE TITLE
Error: "No module named 'lifecycle.auth.job_family" 

### ISSUE THREAD

**Issue by connorsisacat** [TheRacetrack/racetrack#507]
@iszulcdeepsense 

Error: "No module named 'lifecycle.auth.job_family" when running racetrack plugin install of latest docker-infrastructure.

Suspect it might be due to a missing release of racetrack client since job_family was introduced as auth around 2-3 weeks ago in docker-infrastructure-1.5.1. (commit 9bc4d3584e02a91c1f7b050e81e0fe91dd86e2cf (plugin-docker-infrastructure)).

Latest working version seems to be docker-infrastructure-1.5.0, since I can run racetrack plugin install docker-infrastrucure-1.5.0.zip just fine.

**Comment by iszulcdeepsense** [comment]
@connorsisacat  There's a document https://github.com/TheRacetrack/plugin-docker-infrastructure/blob/acc1b886e7be7b9f42473d2e23e63a2a68dba871/docs/compatibility.md that has a plugin compatibility table. According to it, docker-infrastructure plugin in version 1.5.1 is compatible with Racetrack version `> 2.31.0`, which wasn't officially released yet, as you noted.

You must have had an incompatible Racetrack version. To fix this, you can either:
- wait until next Racetrack version is released and upgrade to it. It should happen soon.
- Use *Unreleased* version of Racetrack, taken from master branch
- Use older version of docker-infrastructure plugin. Plugin version 1.5.0 is compatible with Racetrack version >= 2.24.0.

**Comment by connorsisacat** [comment]
@iszulcdeepsense 

Ahh, that makes sense.
It seems I misread the plugin table as >= 2.31.0, and thought my version of Racetrack (2.31.0) would be compatible. 
Thanks for reply! :)
