### ISSUE TITLE
Treat async job call 404 response as error

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#508]
When a job returns 404 error, it may be confused with Pub's 404 response returned by async job call.

When async job call is completed, Pub takes the response returned from a Job, saves it in a database, and forwards it exactly as it is.
In case a **job** returned 404 Not Found response, Pub will return it too.
However, this might be confused with the 404 status returned by Pub in case of a missing task (when user asks for non existing task ID).

According to https://theracetrack.github.io/racetrack/docs/user/async-job-calls/#2-polling-for-the-result

> GET /pub/async/task/{task_id}/poll
> 404 Not Found - This error indicates that the task ID provided is invalid or the task is not found.

Let's treat 404 response of a job as error, not a successful job call.

**Comment by JosefAssadERST** [comment]
> Let's treat 404 response of a job as error, not a successful job call.

Agree. PUB will only forward a request if it knows it the backing job exists, so receiving a 404 back should indeed generate an HTTP error code. [502](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502) is my vote.
