### ISSUE TITLE
Explicit job type versions

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#59]
Let's make the job type versions explicit in manifest files.

## Context
We'd like to support multiple job type versions (of one language wrapper) in Racetrack.
This would be particularly useful for job types provided by plugins.
Plugin can be changed and a new one job type can be released,
but sometimes we'd like to keep the old one too for compatiblity reasons.

## Proposed solution
If a user wants to use a specific version, he declares that explicitly in a YAML manifest:
```yaml
lang: python3-mllab:1.2.0
```

Note: If the version has to be explicitly provided, this feature isn't backwards compatible.

In plugins providing the job types
a developer will declare which version is shipped along with the plugin:
```python
class Plugin:
    def fatman_job_types(self) -> Dict[str, Tuple[Path, Path]]:
        return {
            'python3-mllab:1.2.0': (
                self.plugin_dir / 'base.mllab-3.9-bullseye.Dockerfile',
                self.plugin_dir / 'fatman-template.Dockerfile',
            ),
        }
```

**Comment by JosefAssadERST** [comment]
> If the version has to be explicitly provided, this feature isn't backwards compatible

Good point. Probably the current ERST userrs won't be thrilled to have to redeloy, but again it's a one-time task for what I think is a pretty valuable function. @jsandroos thoughts?

We'll have to be explicit in the design why we're choosing to not do default versions like latest, because when others come to Racetrack it will be something they wonder about, especially if they compare it in their mind to docker.

> In plugins providing the job types a developer will declare which versions are shipped along with the plugin

Ah are you sure this is the best way? The plugin will just grow and grow. I can't think of any other plugin architecture where a plugin codebase contains all possible versions at the same time.

**Comment by iszulcdeepsense** [comment]
> Ah are you sure this is the best way? The plugin will just grow and grow. I can't think of any other plugin architecture where a plugin codebase contains all possible versions at the same time.

Good point. I missed to change that. It should be "which version is shipped with the plugin". There's no point to provide multiple versions in one plugin. It should always come with a one matching the plugin version. Furthermore, this job type version can be taken from the plugin manifest automatically, so there's no need to change the codebase every time, see here 
https://github.com/TheRacetrack/plugin-go-job-type/blob/14724e20168cf3c9c2771591a366bc7e4eaf79a9/golang-job-type/plugin.py#L12

**Comment by JosefAssadERST** [comment]
> > Ah are you sure this is the best way? The plugin will just grow and grow. I can't think of any other plugin architecture where a plugin codebase contains all possible versions at the same time.
> 
> Good point. I missed to change that. It should be "which version is shipped with the plugin". There's no point to provide multiple versions in one plugin. Instead, there can be many plugins, selectively being activated or deactivated. Furthermore, this job type version can be taken from the plugin manifest automatically, so there's no need to change the codebase every time, see here https://github.com/TheRacetrack/plugin-go-job-type/blob/14724e20168cf3c9c2771591a366bc7e4eaf79a9/golang-job-type/plugin.py#L12

🥓
