### ISSUE TITLE
Evaluate database name based on the cluster name

### ISSUE THREAD

**Issue by iszulcdeepsense** [TheRacetrack/racetrack#80]

**Comment by JosefAssadERST** [comment]
Ah, is this a minor ERSTism that's being introduced?

**Comment by iszulcdeepsense** [comment]
> Ah, is this a minor ERSTism that's being introduced?

A sort of, but I'm trying to do it in a generic manner. It's an opt-in feature allowing to use vars in database name, eg. `POSTGRES_DB=racetrack-{CLUSTER_NAME}` so it's getting evaluated automatically without having to keep distinct kustomize resources for each environment (which would enforce harder branches management).

Thus it has wider possibilities, though it's especially useful for ERST purposes, but maybe for other things too. Fortunately, it still supports hardcoded database names as usual, so it doesn't enforce new politics on others.
