### ISSUE TITLE
New job type "HUGO"

### ISSUE THREAD

**Issue by klauscramer** [TheRacetrack/racetrack#88]
Can you create HUGO as a new job type?

**Comment by iszulcdeepsense** [comment]
I need to take a look at this framework first, but it looks promising. There shouldn't be a problem.

**Comment by JosefAssadERST** [comment]
Yeah I think Hugo is pretty easy to make a plugin for. Plenty of opportunity for features too, like a theeme selector in the fatman.yaml for example, or exposing hits in a metrics endpoint.

I think @klauscramer wants it in order to show people that RT is more than just ML models.

**Comment by iszulcdeepsense** [comment]
HUGO job type is ready. There is a dedicated plugin handling this: https://github.com/TheRacetrack/plugin-hugo-job-type

It will be compatible with Racetrack, once https://github.com/TheRacetrack/racetrack/pull/114 is merged.

**Comment by JosefAssadERST** [comment]
@klauscramer when this lands in the C3 dev cluster, we want you to find a use case and make a fatman using this job type. Or you can farm it out to for example Thor?
