### ISSUE TITLE
allow the RT admin to move a fatman from one infrastructure target to another without the fatman owner having to redeploy

### ISSUE THREAD

**Issue by JosefAssadERST** [TheRacetrack/racetrack#98]
When the infrastructure target plugin system has been implemented, and when the 1-to-many for plugin-to-infrastructure-instance is live, it might be a useful feature for the RT admin to look at a Fatman and think "hmm, this should be moved away from this Kubernetes and over to that docker daemon".

We can sort of do this today, but it requires the RT admin to bang their fist on the fatman owner's desk, and demand a redeploy with a different infrastructure target specified.

Do we want to allow this to occur as a function in the RT dashboard?

(off the top of my head, one significant drawback, we will have inconsistency between the configuration in the fatman.yaml and the actual location where the fatman is operating)

Thoughts?

**Comment by iszulcdeepsense** [comment]
Sounds good. I think it would be even possible right away once the infrastructure targets are available.

Right now, as RT admin, you can edit the manifest in an Admin Panel (it's true that it's inconsistent then) and click *Redeploy* to apply changes. In case of moving the fatman somewhere else, you should also remember to delete the old version afterall.

Surely, we can think of making it more user-friendly and convenient.

**Comment by JosefAssadERST** [comment]
> you can edit the manifest in an Admin Panel 

True, so we're already potentially risking inconsistency. I don't like it, but the feature is valuable.

> In case of moving the fatman somewhere else, you should also remember to delete the old version afterall

Shouldn't this be done automatically?

**Comment by JosefAssadERST** [comment]
> But which field in manifest is deployment type specific

I think that's upcoming functionality, right @iszulcdeepsense ?

> user just wants to depl(o)y Fatman to RT, and he doesn't know which deployment method it uses 

Yeah there's a design decision here. When RT is configured with multiple infrastructure target backends, and each of them has multiple instances, at what stage is the decision taken which one of the instances a given job selects? I think these are the options:

1. Allow the job developer to choose; they express it in `fatman.yaml`
2. Require the RT admin to choose (probably lot more complexity in the admin backend, and the fatman is kept in a "holding cell" until the RT admin decides)
3. Implement some sort of policy routing in RT, e.g. "if fatman is pink deploy it to the Windows backend type, instance named LadyGaga; if the fatman is python, deploy it to the Kubernillabackend, the instance dev-c3". Very complex.

I suspect option 1 is the simplest and least "magic". Especially if we allow for admins and potentially owners to use the dashboard to change their decision later on.

**Comment by iszulcdeepsense** [comment]
> I think that's upcoming functionality, right @iszulcdeepsense ?

Right, https://github.com/TheRacetrack/racetrack/issues/101 is the prerequisite for this task. It refers to manifest field too, so we can move that discussion there.

Good thoughts about who makes the decision about infrastructure target.
I agree, option 1 is the simplest one.
Additionally, maybe there can be a default infra target specified by admin. So in case of 

> he doesn't know which deployment method it uses

user can leave it empty, and admin makes that decision on his behalf (default comes in). He can always move it somewhere else later on.

**Comment by JosefAssadERST** [comment]
> maybe there can be a default infra target specified by admin

Yeah if it isn't a lot more complexity to implement.
